version: '3.8'

services:
  web:
    platform: linux/arm64
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=bugbrewer.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery

  redis:
    image: redis:latest
    platform: linux/arm64
    ports:
      - "6379:6379"

  celery:
    platform: linux/arm64
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=bugbrewer.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHROME_BIN=/usr/bin/chrome
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
    command: celery -A bugbrewer worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis 