version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=bugbrewer.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery

  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=bugbrewer.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHROME_BIN=/usr/bin/chrome
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
    command: celery -A bugbrewer worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis 

volumes:
  redis_data: 