# Generated by Django 5.2 on 2025-04-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('asset_type', models.CharField(choices=[('domain', 'Domain'), ('subdomain', 'Subdomain')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ignored Asset',
                'verbose_name_plural': 'Ignored Assets',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='module',
            name='python_module',
            field=models.CharField(choices=[('feroxbuster_scanner', 'feroxbuster_scanner'), ('ffuf_scanner', 'ffuf_scanner'), ('nmap_scanner', 'nmap_scanner'), ('nuclei_scanner', 'nuclei_scanner'), ('ping_scanner', 'ping_scanner'), ('subdomain_recon', 'subdomain_recon'), ('subdomain_scanner', 'subdomain_scanner'), ('test_scanner', 'test_scanner')], help_text="Name of the Python module to run (e.g., 'ping_scanner')", max_length=255),
        ),
    ]
