# Generated by Django 5.2 on 2025-05-03 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_ignoredasset_alter_module_python_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='python_module',
            field=models.CharField(choices=[('feroxbuster_scanner', 'feroxbuster_scanner'), ('ffuf_scanner', 'ffuf_scanner'), ('nmap_scanner', 'nmap_scanner'), ('nuclei_scanner', 'nuclei_scanner'), ('ping_scanner', 'ping_scanner'), ('subdomain_recon', 'subdomain_recon'), ('subdomain_scanner', 'subdomain_scanner'), ('subdomain_takeover_scanner', 'subdomain_takeover_scanner'), ('test_scanner', 'test_scanner')], help_text="Name of the Python module to run (e.g., 'ping_scanner')", max_length=255),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='queued', max_length=10),
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2048)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('PATCH', 'PATCH')], default='GET', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_interesting', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='scanner.asset')),
                ('findings', models.ManyToManyField(blank=True, related_name='endpoints', to='scanner.finding')),
                ('scans', models.ManyToManyField(blank=True, related_name='endpoints', to='scanner.scan')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='scanner.subdomain')),
                ('tags', models.ManyToManyField(blank=True, to='scanner.tag')),
            ],
            options={
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['path'], name='scanner_end_path_f77854_idx'), models.Index(fields=['status_code'], name='scanner_end_status__c138ae_idx'), models.Index(fields=['is_interesting'], name='scanner_end_is_inte_5cba21_idx'), models.Index(fields=['discovered_at'], name='scanner_end_discove_7c21e3_idx')],
                'unique_together': {('asset', 'path', 'method'), ('subdomain', 'path', 'method')},
            },
        ),
    ]
