# Generated by Django 5.2 on 2025-05-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_module_python_module_alter_scan_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='stopped', max_length=10)),
                ('scan_interval', models.IntegerField(default=24, help_text='Scan interval in hours')),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('next_scan', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assets', models.ManyToManyField(related_name='continuous_scans', to='scanner.asset')),
                ('modules', models.ManyToManyField(related_name='continuous_scans', to='scanner.module')),
            ],
        ),
    ]
