# Generated by Django 5.2 on 2025-05-03 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_continuousscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousscan',
            name='assets',
            field=models.ManyToManyField(to='scanner.asset'),
        ),
        migrations.AlterField(
            model_name='continuousscan',
            name='modules',
            field=models.ManyToManyField(to='scanner.module'),
        ),
        migrations.AlterField(
            model_name='continuousscan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='continuousscan',
            name='scan_interval',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='continuousscan',
            name='status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('paused', 'Paused')], default='stopped', max_length=10),
        ),
    ]
