# Generated by Django 5.2 on 2025-05-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_alter_continuousscan_assets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuousscan',
            name='assets',
        ),
    ]
